<?php

echo"<ul class=\"nav navbar-nav\">";
echo"                    <li ><a class=\"navbar-brand\" href=\"/~hollimi/Home.php\">Home</a></li>";
echo"		    </li>";
echo"                    <li class=\"dropdown\">";
echo"			<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Rooms";
echo"        			<span class=\"caret\"></span>";
echo"			</a>";
echo"        		<ul class=\"dropdown-menu\">";
echo"          			<li><a href=\"a1.php\">A.1</a></li>";
echo"          			<li><a href=\"a2.php\">A.2</a></li>";
echo"	    			<li><a href=\"a3.php\">A.3</a></li>";

echo"        		</ul>";
echo"		    </li>";
echo"                    <li class=\"dropdown\">";
echo"			<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Patients";
echo"        			<span class=\"caret\"></span>";
echo"			</a>";
echo"        		<ul class=\"dropdown-menu\">";
echo"          			<li><a href=\"b1.php\">B.1</a></li>";
echo"          			<li><a href=\"b2.php\">B.2</a></li>";
echo"	    			<li><a href=\"b3.php\">B.3</a></li>";
echo"				<li><a href=\"b4.php\">B.4</a></li>";
echo"				<li><a href=\"b5.php\">B.5</a></li>	";
echo"				<li><a href=\"b6.php\">B.6</a></li>";
echo"				<li><a href=\"b7.php\">B.7</a></li>";
echo"				<li><a href=\"b8.php\">B.8</a></li>";
echo"				<li><a href=\"b9.php\">B.9</a></li>";
echo"				<li><a href=\"b10.php\">B.10</a></li>";
echo"        		</ul>";
echo"		    </li>";
echo"                    <li class=\"dropdown\">";
echo"			<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Diagnosis & Treatment";
echo"        			<span class=\"caret\"></span>";
echo"			</a>";
echo"        		<ul class=\"dropdown-menu\">";
echo"          			<li><a href=\"c1.php\">C.1</a></li>";
echo"          			<li><a href=\"c2.php\">C.2</a></li>";
echo"	    			<li><a href=\"c3.php\">C.3</a></li>";
echo"				<li><a href=\"c4.php\">C.4</a></li>";
echo"				<li><a href=\"c5.php\">C.5</a></li>	";
echo"				<li><a href=\"c6.php\">C.6</a></li>";
echo"				<li><a href=\"c7.php\">C.7</a></li>";
echo"				<li><a href=\"c8.php\">C.8</a></li>";
echo"        		</ul>";
echo"		    </li>";
echo"                    <li class=\"dropdown\">";
echo"			<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Employees";
echo"        			<span class=\"caret\"></span>";
echo"			</a>";
echo"        		<ul class=\"dropdown-menu\">";
echo"          			<li><a href=\"d1.php\">D.1</a></li>";
echo"          			<li><a href=\"d2.php\">D.2</a></li>";
echo"	    			<li><a href=\"d3.php\">D.3</a></li>";
echo"				<li><a href=\"d4.php\">D.4</a></li>";
echo"				<li><a href=\"d5.php\">D.5</a></li>	";
echo"				<li><a href=\"d6.php\">D.6</a></li>";
echo"				<li><a href=\"d7.php\">D.7</a></li>";
echo"        		</ul>";
echo"		    </li>";
echo"                    <li ><a class=\"navbar-brand\" href=\"/~hollimi/CustomQuery.php\">Custom Query</a></li>";
echo"                </ul>";
?>